In [1]:
### Import File ###
import csv
import numpy as np

""" 
Column Names: 
['Date', 'Name', 'Team', 'Season', 'Round',
    'Home Team', 'Away Team', 'Home Score', 'Away Score', 'Margin',
    'Disposals', 'Kicks', 'Marks', 'Handballs', 'Goals',
    'Behinds', 'Hitouts', 'Tackles', 'Rebounds', 'Inside 50s',
    'Clearances', 'Clangers', 'Frees For', 'Frees Against', 'Contested Pos',
    'Uncontested Pos', 'Contested Marks', 'Marks Inside 50', 'One Percenters', 'Goal Assists',
    'Brownlow Votes', 'TOG']
"""
with open("RawData.csv") as csvFile:
    csvData = csv.reader(csvFile)
    
    headRow = next(csvData)
    indCol=[i for i in range(7,30)] # Columns of independent variables
    trnList  = [] # Train data
    tstList = [] # Test data
    
    for row in csvData:
        year = int(float(row[3]))
        
        # Training set
        if year < 2016:
            trnList.append([])
            for i in range(0,len(headRow)):
                if i==3: # Year
                    trnList[-1].append( round( float( (row[i]) ) ) )
                elif 7 <= i <= 30: # Integer Data
                    trnList[-1].append( float( (row[i]) ) ) 
                else: # String data
                    trnList[-1].append(str(row[i]))
        
        # Testing set
        else:   
            tstList.append([])
            for i in range(0,len(headRow)):
                if i==3: # Year
                    tstList[-1].append( round( float( (row[i]) ) ) )
                elif 7 <= i <= 30: # Integer Data
                    tstList[-1].append( float( (row[i]) ) ) 
                else: # String data
                    tstList[-1].append( str(row[i]))
   

In [4]:
import pandas as pd
import scipy
import matplotlib.pyplot as plt

trnDF = pd.DataFrame(trnData)
tstDF = pd.DataFrame(tstData)

In [ ]:
### K-Nearest Neighbours ###
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
import numpy as np

# Standardise data
trnScale = np.zeros((len(trnData['Date']), len(indCol)))
tstScale = np.zeros((len(trnData['Date']), len(indCol)))

for i in indCol:
    header = headRow[i]
    hdScale = StandardScaler()
    
    hdScale.fit(trnData[header])
    trnScale[i] = hdScale.transform(trnData[header])
    
    hdScale.fit(tstData[header])
    tstScale[i] = hdScale.transform(tstData[header])

knnModel = NearestNeighbors(n_neighbors=5,algorithm='ball_tree').fit(trnScale)



In [2]:
import numpy as np

theAr = np.array([[1,2,3],[3,5,6],[7,8,9]])
print(theAr)
theAr[0] = [10,11,12]
print(theAr)

[[1 2 3]
 [3 5 6]
 [7 8 9]]
[[10 11 12]
 [ 3  5  6]
 [ 7  8  9]]
